Fix integration test & more user_id clean-up (#56, resolves #55)
* Fix Decks' description, currently incorrectly set to the user ID

* rest_api.py's update_deck no longer uses Deck's user_id

Fixes integration tests, previously failing with::
```
>       updated_deck = self.get_deck(deck.id, deck.user_id)
E       AttributeError: 'Deck' object has no attribute 'user_id'

tinycards/networking/rest_api.py:277: AttributeError
```

* rest_api.py's get_deck no longer sets user_id on Deck object

* Fix example, where Deck's description would be set to user ID